name: simple sparse checkout
description: do sparse checkout
branding:
  icon: git-branch
  color: orange
inputs:
  directory:
    description: Specify checkout directory. You can specify multiple by separating them with spaces.
    required: true
  depth:
    description: specify depth for git clone
    required: false
    default: '1'
  token:
    description: github access token
    required: true
runs:
  using: composite
  steps:
    - name: sparse checkout
      shell: bash
      run: |
        git clone --filter=blob:none --no-checkout --depth ${{ inputs.depth }} --sparse https://${GITHUB_ACTOR}:${{ inputs.token }}@github.com/${GITHUB_REPOSITORY}.git .
        git sparse-checkout init --cone
        git sparse-checkout add ${{ inputs.directory }}
        git checkout ${GITHUB_SHA}
